`default_nettype none

// CaveBanpresto-local save-state adapter for an already-existing synchronous
// RAM port.
//
// The adapter owns no storage and adds no RAM port.  Integration must mux the
// signals below onto one existing game RAM port only while port_takeover_o is
// asserted.  takeover_permitted_i must be generated by the quiesce controller
// and be stable before a read or write request is presented.
//
// Port timing contract:
// - port_rd_o/port_wr_o are one-cycle issue strobes sampled on clk_i.
// - port_dout_i is valid READ_LATENCY cycles after port_rd_o is sampled.
// - the memory port has no ready/back-pressure signal.
// - req_addr is an element index, not a byte address.
//
// A requester holds a command through rsp_ack.  After any acknowledgement this
// responder waits for all command bits to deassert, preventing a held request
// from issuing the same memory operation more than once.
module CaveBanprestoSaveStateRamOwner #(
	parameter [7:0] OWNER_INDEX = 8'd4,
	parameter integer ELEMENT_WIDTH = 16,
	parameter integer ELEMENT_COUNT = 32768,
	parameter integer READ_LATENCY = 1
) (
	input  wire clk_i,
	input  wire reset_i,
	input  wire takeover_permitted_i,

	output logic port_takeover_o,
	output logic port_rd_o,
	output logic port_wr_o,
	output logic [((ELEMENT_COUNT <= 1) ?
	               1 : $clog2(ELEMENT_COUNT))-1:0] port_addr_o,
	output logic [ELEMENT_WIDTH-1:0] port_din_o,
	input  wire  [ELEMENT_WIDTH-1:0] port_dout_i,

	cavebanpresto_ssbus_if.responder ssbus
);

	localparam integer PORT_ADDRESS_WIDTH =
		(ELEMENT_COUNT <= 1) ? 1 : $clog2(ELEMENT_COUNT);
	localparam integer READ_WAIT_COUNT_WIDTH =
		(READ_LATENCY <= 1) ? 1 : $clog2(READ_LATENCY);

	localparam [31:0] ELEMENT_COUNT_32 = ELEMENT_COUNT;
	localparam [1:0] ELEMENT_WIDTH_CODE =
		(ELEMENT_WIDTH == 8)  ? 2'd0 :
		(ELEMENT_WIDTH == 16) ? 2'd1 :
		(ELEMENT_WIDTH == 32) ? 2'd2 :
		                        2'd3;
	localparam [31:0] READ_WAIT_TERMINAL_32 =
		(READ_LATENCY <= 1) ? 32'd0 : READ_LATENCY - 1;
	localparam [READ_WAIT_COUNT_WIDTH-1:0] READ_WAIT_TERMINAL =
		READ_WAIT_TERMINAL_32[READ_WAIT_COUNT_WIDTH-1:0];
	localparam PARAMETERS_VALID =
		((ELEMENT_WIDTH == 8)  |
		 (ELEMENT_WIDTH == 16) |
		 (ELEMENT_WIDTH == 32) |
		 (ELEMENT_WIDTH == 64)) &
		(ELEMENT_COUNT > 0) &
		(ELEMENT_COUNT <= 32'h7FFF_FFFF) &
		(READ_LATENCY > 0);

	typedef enum logic [1:0] {
		StIdle        = 2'd0,
		StReadWait    = 2'd1,
		StWaitRelease = 2'd2
	} state_e;

	// Justification (reg-a): holds transaction state across a synchronous RAM
	// read and through the held-request release interval.
	state_e state_q;

	// Justification (reg-a): preserves the accepted read address and memory
	// address while the synchronous RAM response is pending. Read payloads are
	// canonical zero, so each RAM owner needs no duplicate 64-bit payload latch.
	logic [31:0] req_addr_q;
	logic [PORT_ADDRESS_WIDTH-1:0] port_addr_q;

	// Justification (reg-a): counts the configured synchronous read latency.
	logic [READ_WAIT_COUNT_WIDTH-1:0] read_wait_count_q;

	logic  [3:0] request_command;
	logic        request_selected;
	logic        request_command_legal;
	logic        address_valid;
	logic        read_payload_canonical;
	logic        read_request_matches;
	logic [63:0] read_response_data;

	assign request_command = {
		ssbus.req_query,
		ssbus.req_validate,
		ssbus.req_write,
		ssbus.req_read
	};
	assign request_selected =
		ssbus.req_select == OWNER_INDEX && (|request_command);
	assign request_command_legal =
		(request_command == 4'b0001) |
		(request_command == 4'b0010) |
		(request_command == 4'b0100) |
		(request_command == 4'b1000);
	assign address_valid = ssbus.req_addr < ELEMENT_COUNT_32;
	assign read_payload_canonical = ssbus.req_data === 64'd0;
	assign read_request_matches =
		(ssbus.req_select == OWNER_INDEX) &
		(request_command == 4'b0001) &
		(ssbus.req_addr == req_addr_q) &
		read_payload_canonical;

	always_comb begin
		read_response_data = 64'd0;
		read_response_data[ELEMENT_WIDTH-1:0] = port_dout_i;
	end

	// The existing RAM samples these combinational issue controls on clk_i.
	// Their defaults are deterministic and no control can assert while reset or
	// without the external takeover permission.
	always_comb begin
		port_takeover_o = 1'b0;
		port_rd_o = 1'b0;
		port_wr_o = 1'b0;
		port_addr_o = {PORT_ADDRESS_WIDTH{1'b0}};
		port_din_o = {ELEMENT_WIDTH{1'b0}};

		if (!reset_i) begin
			case (state_q)
				StIdle: begin
					if (PARAMETERS_VALID &&
					    request_selected &&
					    request_command_legal &&
					    address_valid &&
					    takeover_permitted_i &&
					    (ssbus.req_write |
					     (ssbus.req_read &
					      read_payload_canonical))) begin
						port_takeover_o = 1'b1;
						port_addr_o =
							ssbus.req_addr[
								PORT_ADDRESS_WIDTH-1:0
							];
						port_din_o =
							ssbus.req_data[
								ELEMENT_WIDTH-1:0
							];
						port_rd_o = ssbus.req_read;
						port_wr_o = ssbus.req_write;
					end
				end

				StReadWait: begin
					if (takeover_permitted_i &&
					    read_request_matches) begin
						port_takeover_o = 1'b1;
						port_addr_o = port_addr_q;
					end
				end

				default: begin
					port_takeover_o = 1'b0;
					port_rd_o = 1'b0;
					port_wr_o = 1'b0;
					port_addr_o =
						{PORT_ADDRESS_WIDTH{1'b0}};
					port_din_o =
						{ELEMENT_WIDTH{1'b0}};
				end
			endcase
		end
	end

	always_ff @(posedge clk_i) begin
		if (reset_i) begin
			state_q <= StIdle;
			req_addr_q <= 32'd0;
			port_addr_q <= {PORT_ADDRESS_WIDTH{1'b0}};
			read_wait_count_q <=
				{READ_WAIT_COUNT_WIDTH{1'b0}};
			ssbus.rsp_data <= 64'd0;
			ssbus.rsp_ack <= 1'b0;
			ssbus.rsp_error <= 1'b0;
		end else begin
			// Responses are single-cycle pulses.  Every no-response cycle
			// returns deterministic zeros.
			ssbus.rsp_data <= 64'd0;
			ssbus.rsp_ack <= 1'b0;
			ssbus.rsp_error <= 1'b0;

			case (state_q)
				StIdle: begin
					read_wait_count_q <=
						{READ_WAIT_COUNT_WIDTH{1'b0}};

					if (request_selected) begin
						if (!PARAMETERS_VALID ||
						    !request_command_legal) begin
							ssbus.rsp_ack <= 1'b1;
							ssbus.rsp_error <= 1'b1;
							state_q <= StWaitRelease;
						end else if (ssbus.req_query) begin
							ssbus.rsp_data <=
								ssbus.query_descriptor(
									OWNER_INDEX,
									ELEMENT_COUNT_32,
									ELEMENT_WIDTH_CODE
								);
							ssbus.rsp_ack <= 1'b1;
							state_q <= StWaitRelease;
						end else if (ssbus.req_validate) begin
							ssbus.rsp_ack <= 1'b1;
							ssbus.rsp_error <=
								!address_valid;
							state_q <= StWaitRelease;
						end else if (ssbus.req_read &&
						             !read_payload_canonical) begin
							// Read data is unused by the RAM port.
							// Known-zero admission removes a duplicate
							// pending payload latch while preserving
							// fail-closed mutation handling.
							ssbus.rsp_ack <= 1'b1;
							ssbus.rsp_error <= 1'b1;
							state_q <= StWaitRelease;
						end else if (!address_valid ||
						             !takeover_permitted_i) begin
							ssbus.rsp_ack <= 1'b1;
							ssbus.rsp_error <= 1'b1;
							state_q <= StWaitRelease;
						end else if (ssbus.req_write) begin
							// The existing RAM accepts the
							// combinational port_wr_o strobe
							// on this same edge.
							ssbus.rsp_ack <= 1'b1;
							state_q <= StWaitRelease;
						end else begin
							// The existing RAM accepts
							// port_rd_o on this edge.
							req_addr_q <= ssbus.req_addr;
							port_addr_q <=
								ssbus.req_addr[
									PORT_ADDRESS_WIDTH-1:0
								];
							state_q <= StReadWait;
						end
					end
				end

				StReadWait: begin
					if (!read_request_matches) begin
						// An abandoned/changed request is
						// canceled without a late response.
						read_wait_count_q <=
							{READ_WAIT_COUNT_WIDTH{1'b0}};
						state_q <= StWaitRelease;
					end else if (!takeover_permitted_i) begin
						ssbus.rsp_ack <= 1'b1;
						ssbus.rsp_error <= 1'b1;
						read_wait_count_q <=
							{READ_WAIT_COUNT_WIDTH{1'b0}};
						state_q <= StWaitRelease;
					end else if (read_wait_count_q ==
					             READ_WAIT_TERMINAL) begin
						ssbus.rsp_data <= read_response_data;
						ssbus.rsp_ack <= 1'b1;
						read_wait_count_q <=
							{READ_WAIT_COUNT_WIDTH{1'b0}};
						state_q <= StWaitRelease;
					end else begin
						read_wait_count_q <=
							read_wait_count_q + 1'b1;
					end
				end

				StWaitRelease: begin
					if (!ssbus.command_active()) begin
						state_q <= StIdle;
					end
				end

				default: begin
					state_q <= StIdle;
					read_wait_count_q <=
						{READ_WAIT_COUNT_WIDTH{1'b0}};
				end
			endcase
		end
	end

endmodule

`default_nettype wire
